name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Heloo World!"
          echo "Heloo Viraj!"
      - name: Print goodbye
        run: echo "Bye..Bye"
